apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: router
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/holybaechu/homelab.git'
    targetRevision: HEAD
    path: apps/router
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: router
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true