apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router
  namespace: router
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/allow-ip-block: "192.168.0.0/24"
spec:
  tls:
    - hosts:
        - "router.home.holyb.xyz"
      secretName: home-holyb-xyz-tls
  ingressClassName: nginx
  rules:
    - host: "router.home.holyb.xyz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router
                port:
                  number: 80