services:
  filebrowser:
    image: gtstef/filebrowser:1.1.6-beta
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - proxy
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml" # overrides the default path which is ./config.yaml
      FILEBROWSER_ADMIN_PASSWORD: ${FILEBROWSER_ADMIN_PASSWORD:-changeme}
      TZ: ${TZ:-Asia/Seoul}
    volumes:
      - /root/downloads:/downloads
      - /root/music:/music
      - /root/podcasts:/podcasts
      - /root/playlists:/playlists
      - ./data:/home/filebrowser/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.home.holyb.xyz`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls.certresolver=cloudflare"
      - "traefik.http.routers.filebrowser.middlewares=local-network-only@file"
      - "traefik.http.routers.filebrowser.service=filebrowser-service"
      - "traefik.http.services.filebrowser-service.loadbalancer.server.port=80"

networks:
  proxy:
    name: proxy
