services:
  minecraft:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      LEVEL_TYPE: "FLAT"
      ENABLE_WHITELIST: "TRUE"
    volumes:
      - /home/docker/data/minecraft:/data
