services:
  minecraft:
    image: itzg/minecraft-server:latest
    pull_policy: daily # Let it update every restart
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: TRUE
      
      TYPE: PAPER
      VERSION: 1.21.10

      LEVEL_TYPE: FLAT
      GENERATOR_SETTINGS: >-
        {
            "layers": [
                {
                    "block": "minecraft:bedrock",
                    "height": 1
                },
                {
                    "block": "minecraft:dirt",
                    "height": 32
                },
                {
                    "block": "minecraft:grass_block",
                    "height": 1
                }
            ]
        }
      
      ENABLE_WHITELIST: TRUE
      MODRINTH_PROJECTS: |
        worldedit
        axiom-paper-plugin
        viaversion
    volumes:
      - /home/docker/data/minecraft:/data
