services:
  proxy:
    image: itzg/mc-proxy:latest

    tty: true
    stdin_open: true
    
    restart: unless-stopped
    
    ports:
      - "25565:25577"
    
    environment:
      TYPE: VELOCITY
 
      MINECRAFT_VERSION: 1.21.11
      MODRINTH_PROJECTS: |
        viaversion
        luckperms:GZjsuCmU
        raknetify
    
    volumes:
      - ./velocity.toml:/server/velocity.toml
      - proxy_data:/server
    
    secrets:
      - forwarding_secret
  
  flat:
    image: itzg/minecraft-server:latest
    
    tty: true
    stdin_open: true
    
    restart: unless-stopped
    
    environment:
      EULA: TRUE
      
      TYPE: PAPER
      VERSION: 1.21.11

      LEVEL_TYPE: FLAT
      GENERATOR_SETTINGS: >-
        {
            "layers": [
                {
                    "block": "minecraft:bedrock",
                    "height": 1
                },
                {
                    "block": "minecraft:dirt",
                    "height": 32
                },
                {
                    "block": "minecraft:grass_block",
                    "height": 1
                }
            ]
        }
      
      ONLINE_MODE: FALSE
      ENFORCE_SECURE_PROFILE: "FALSE"
      OP_PERMISSION_LEVEL: 2
      ENABLE_WHITELIST: TRUE
      VIEW_DISTANCE: 16
      SIMULATION_DISTANCE: 8

      MODRINTH_PROJECTS: |
        worldedit
        axiom-paper-plugin
        luckperms:OrIs0S6b
        coreprotect:HD2IvrxS

      PATCH_DEFINITIONS: "/patches"
      REPLACE_ENV_VARIABLE_PREFIX: "CFG_"
      CFG_FORWARDING_SECRET: ${CFG_FORWARDING_SECRET}

    volumes:
      - ./patches/paper-global-patch.json:/patches/paper-global-patch.json
      - ./patches/luckperms-patch.json:/patches/luckperms-patch.json
      - flat_data:/data

volumes:
  proxy_data:
  flat_data:

secrets:
  forwarding_secret:
    environment: "CFG_FORWARDING_SECRET"