services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: 1000:1000
    networks:
      - proxy
    volumes:
      - /home/docker/data/navidrome:/data
      - /home/docker/music:/music:ro
    environment:
      - ND_SCANSCHEDULE=@every 1h
      - ND_LOGLEVEL=info
      - ND_ENABLESHARING=true
      - ND_LASTFM_APIKEY
      - ND_LASTFM_SECRET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`navidrome.holyb.xyz`)"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.routers.navidrome.tls.certresolver=cloudflare"
      - "traefik.http.routers.navidrome.service=navidrome-service"
      - "traefik.http.services.navidrome-service.loadbalancer.server.port=4533"

networks:
  proxy:
    name: proxy
