- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: sunday

    - size: full
      widgets:
        - type: search
          search-engine: duckduckgo
          autofocus: true

    - size: small
      widgets:
        - type: weather
          location: Changwon
          units: metric
          hour-format: 12h
        - $include: widgets/speedtest-tracker.yml