apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.2
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true
resources:
  - namespace.yaml
  - cluster-issuer.yaml
  - cloudflare-secret.yaml