[global]
  e2dsa
  e2ts
  ansi
  rproxy: -1
  xff-src: 192.168.0.4
  name: copyparty.hchu.me
  localtime
  gsel
  lang: kor
  grid
  p: 3923

[/public]
  /srv/public
  accs:
    r: *
    A: holybaechu

[/shared-readonly]
  /srv/shared-readonly
  accs:
    r: siregon72, ezmin1104, sieon, emuyoz, ys100503
    A: holybaechu

[/downloads]
  /srv/downloads
  accs:
    r: holybaechu
    A: holybaechu
