apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/holybaechu/homelab.git'
    targetRevision: HEAD
    path: apps/proxmox
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: proxmox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true