---
- name: Restart adguardhome
  ansible.builtin.service:
    name: adguardhome
    state: restarted

- name: Restart adguard nftables
  ansible.builtin.service:
    name: nftables
    state: restarted
