controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: k8s.io/ingress-nginx
  
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.0.200

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    
  replicaCount: 1