apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - https://github.com/rook/rook//deploy/examples?ref=v1.17.7
  - operator.yaml
  - cluster.yaml
  - storageclass.yaml