all:
  vars:
    ansible_user: root
  children:
    pve_hosts:
      hosts:
        pve:
          ansible_host: 192.168.0.2
    alpine:
      hosts:
        dns:
          ansible_host: 192.168.0.3
        edge:
          ansible_host: 192.168.0.4
        files:
          ansible_host: 192.168.0.7
    debian:
      hosts:
        tailnet:
          ansible_host: 192.168.0.5
        downloads:
          ansible_host: 192.168.0.6
        minecraft:
          ansible_host: 192.168.0.8
        hermes:
          ansible_host: 192.168.0.9
    svc_dns:
      hosts:
        dns:
    svc_edge:
      hosts:
        edge:
    svc_tailnet:
      hosts:
        tailnet:
    svc_downloads:
      hosts:
        downloads:
    svc_files:
      hosts:
        files:
    svc_minecraft:
      hosts:
        minecraft:
    svc_hermes:
      hosts:
        hermes:
