all:
  vars:
    ansible_user: root
  children:
    pve_hosts:
      hosts:
        pve:
          ansible_host: 192.168.0.2
    debian:
      hosts:
        tailnet:
          ansible_host: 192.168.0.4
        docker_apps:
          ansible_host: 192.168.0.3
    svc_tailnet:
      hosts:
        tailnet:
    svc_docker_apps:
      hosts:
        docker_apps:
