all:
  vars:
    ansible_user: root
  children:
    pve_hosts:
      hosts:
        pve:
          ansible_host: 192.168.0.2
    alpine:
      hosts:
        edge:
          ansible_host: 192.168.0.4
        dns:
          ansible_host: 192.168.0.3
        files:
          ansible_host: 192.168.0.7
    debian:
      hosts:
        tailnet:
          ansible_host: 192.168.0.5
        downloads:
          ansible_host: 192.168.0.6
        minecraft:
          ansible_host: 192.168.0.8
        hermes:
          ansible_host: 192.168.0.9
    edge:
      hosts:
        edge:
    dns:
      hosts:
        dns:
    tailnet:
      hosts:
        tailnet:
    downloads:
      hosts:
        downloads:
    files:
      hosts:
        files:
    minecraft:
      hosts:
        minecraft:
    hermes:
      hosts:
        hermes:
