---
- name: Reload local CTF Docker systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart local CTF Docker
  ansible.builtin.systemd_service:
    name: docker.service
    state: restarted

