homelab_timezone: Asia/Seoul

service_uid: 1000
service_gid: 1000

homelab_data_lv_name: homelab-data
homelab_data_lv_size: 896G
homelab_data_mount: /var/lib/homelab
homelab_data_device: "/dev/pve/{{ homelab_data_lv_name }}"
