minecraft_user: minecraft
minecraft_group: minecraft
minecraft_uid: 1200
minecraft_gid: 1200

minecraft_base_dir: /var/lib/minecraft
minecraft_paper_dir: /var/lib/minecraft/paper
minecraft_velocity_dir: /var/lib/minecraft/velocity
minecraft_paper_plugins_dir: /var/lib/minecraft/paper/plugins
minecraft_velocity_plugins_dir: /var/lib/minecraft/velocity/plugins
minecraft_allowed_players_file: "{{ playbook_dir }}/../../../apps/minecraft/allowed-players.yml"

minecraft_java_package: openjdk-25-jre-headless
minecraft_java_xms: 1024M
minecraft_java_xmx: 3072M

minecraft_java_port: 25565
minecraft_bedrock_port: 19132
minecraft_paper_bind_address: 127.0.0.1
minecraft_paper_port: 25566
minecraft_motd: "hchu.me Minecraft"
minecraft_max_players: 10
minecraft_floodgate_username_prefix: "."

minecraft_paper_version: "26.1.2"
minecraft_paper_build: 70
minecraft_paper_sha256: 6c59eefe2752f97ee79f83ad0a61fe14865a0976e4ac06597f53de6c44afd6c5

minecraft_velocity_version: "3.5.0-SNAPSHOT"
minecraft_velocity_build: 601
minecraft_velocity_sha256: 0407642d1ed2883100eb823c2805523f191fa637db1f42ac0ec7ef29cbe455a9

minecraft_geyser_version: "2.10.1"
minecraft_geyser_build: 1165
minecraft_geyser_velocity_sha256: 59d0e74afb45000ba18d6fa459f07fd34b3af3ad6357ae4e895c2085d9dc126c

minecraft_floodgate_version: "2.2.5"
minecraft_floodgate_build: 132
minecraft_floodgate_velocity_sha256: f258995043a4869cb6f1ef605110ac1d9066a5b1e1b316495a25b06afa0c1060

minecraft_viaversion_version: "5.9.1"
minecraft_viaversion_url: https://cdn.modrinth.com/data/P1OZGk5p/versions/OGj9YIQN/ViaVersion-5.9.1.jar
minecraft_viaversion_sha512: 7b89f2779c487342f8a77db27583a98868bb20117a4fa68a2e07da0bb62da5aef446bbbc01720a0a983a1ea2e91a6bd26fc947befee140ff1e4e251ebf602cf8
