downloads_mount_path: /downloads
downloads_complete_path: /downloads/complete
downloads_incomplete_path: /downloads/incomplete
copyparty_public_mount_path: /public
proton_wg_interface: wg-proton
proton_server_list_url: https://raw.githubusercontent.com/qdm12/gluetun-servers/14277e92ce8291eb4515cd9af0dfad383a23f145/pkg/servers/protonvpn.json
proton_server_country: Japan
proton_port_forward_only: true
proton_wireguard_address: 10.2.0.2/32
proton_wireguard_endpoint_port: 51820
proton_wireguard_dns: 1.1.1.1
proton_wireguard_allowed_ips: "0.0.0.0/0, ::/0"
proton_natpmp_gateway: 10.2.0.1
qbittorrent_webui_port: 8080
qbittorrent_webui_username: holybaechu
# renovate: datasource=github-releases depName=VueTorrent/VueTorrent versioning=semver extractVersion=^v(?<version>.*)$
qbittorrent_vuetorrent_version: 2.34.0
qbittorrent_vuetorrent_release_url: "https://github.com/VueTorrent/VueTorrent/releases/download/v{{ qbittorrent_vuetorrent_version }}/vuetorrent.zip"
qbittorrent_vuetorrent_sha256: 22f34c20f6a5704e3b37c3ed73956af7bda5536c10458575c52b0618851b665e
qbittorrent_vuetorrent_root: "/opt/vuetorrent/releases/{{ qbittorrent_vuetorrent_version }}"
qbittorrent_vuetorrent_root_current: /opt/vuetorrent/current
qbittorrent_user: qbittorrent
qbittorrent_group: qbittorrent
qbittorrent_uid: "{{ downloads_service_uid }}"
qbittorrent_gid: "{{ downloads_service_gid }}"
qbittorrent_natpmp_env_path: /etc/proton-natpmp-qbt.env
