services:
  copyparty:
    image: copyparty/ac:1.20.1
    container_name: copyparty
    restart: unless-stopped
    user: "1000:1000"
    command:
      - -a
      - ${COPYPARTY_USER_NAME:-admin}:${COPYPARTY_USER_PASSWORD:-changeme}
    volumes:
      - ./:/cfg:z
      - /home/docker/downloads:/downloads:z
      - /home/docker/public:/public:z
    networks:
      - proxy
    environment:
      XDG_CONFIG_HOME: /cfg
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.2
      # enable mimalloc by replacing "NOPE" with "2" for a nice speed-boost (will use twice as much ram)
      PYTHONUNBUFFERED: 1
      # ensures log-messages are not delayed (but can reduce speed a tiny bit)
    stop_grace_period: 15s # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    healthcheck:
      # hide it from logs with "/._" so it matches the default --lf-url filter
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copyparty.rule=Host(`copyparty.holyb.xyz`)"
      - "traefik.http.routers.copyparty.entrypoints=websecure"
      - "traefik.http.routers.copyparty.tls.certresolver=cloudflare"
      - "traefik.http.routers.copyparty.service=copyparty-service"
      - "traefik.http.services.copyparty-service.loadbalancer.server.port=3923"

networks:
  proxy:
    name: proxy
