[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages (both in logfiles and stdout)

  rproxy: -1
  xff-src=lan

[/public]
  /public  # create a volume at "/public", which will be shared with the
  accs:    # "public" volume
    r: *    # everyone gets read access
    rwmda: holybaechu  # the user "ed" gets read-write-move-delete-admin

[/downloads]            # create a volume at "/" (the webroot), which will
  /downloads  # be shared with the "downloads" volume
  accs:
    rwmda: holybaechu  # the user "ed" gets read-write-move-delete-admin
