[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages (both in logfiles and stdout)

  rproxy: -1
  xff-src: lan

  name: copyparty.hchu.me  # Set server name
  spinner: 🎹

  localtime  # Use local timezone instead of UTC
  gsel  # Use CTRL and SHIFT to select files in grid-view
  lang: kor  # Set language to Korean

[/public]
  /public
  accs:
    r: *
    A: holybaechu

[/shared-readonly]
  /shared-readonly
  accs:
    r: siregon72, ezmin1104, sieon, emuyoz
    A: holybaechu

[/bjh_deepfake_contest/제출]
  /bjh_deepfake_contest/제출
  accs:
    w: bjh_deepfake_contest
    A: holybaechu, siregon72

[/bjh_deepfake_contest/샘플]
  /bjh_deepfake_contest/샘플
  accs:
    r: bjh_deepfake_contest
    A: holybaechu, siregon72

[/download]
  /downloads
  accs:
    A: holybaechu

[/music]
  /music
  accs:
    A: holybaechu
