name: traefik

services:
  traefik:
    image: traefik:v3.6.2
    restart: unless-stopped
    env_file: .env
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /srv/docker-apps/traefik:/data:rw
      - /etc/ssl/certs/homelab-pve-root-ca.pem:/etc/ssl/certs/homelab-pve-root-ca.pem:ro
    networks:
      - proxy

networks:
  proxy:
    name: homelab_proxy
