services:
  tailscale:
    image: tailscale/tailscale:v1.96.5
    container_name: tailscale
    restart: unless-stopped
    hostname: ${TAILSCALE_HOSTNAME:-homelab}
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_OUTBOUND_HTTP_PROXY_LISTEN=0.0.0.0:1055
      - TS_EXTRA_ARGS=--accept-routes --advertise-exit-node --advertise-routes=${TAILSCALE_ADVERTISE_ROUTES} --advertise-connector --advertise-tags=tag:connector
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - tailscale-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxy

volumes:
  tailscale-state:

networks:
  proxy:
    external: true