apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-web-ui
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.0.201
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-tcp
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
  - name: bittorrent-tcp
    port: 65084
    targetPort: 65084
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.0.201
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-udp
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
  - name: bittorrent-udp
    port: 65084
    targetPort: 65084
    protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 192.168.0.201