---
- name: Reload isolated CTF executor systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart isolated CTF Docker
  ansible.builtin.systemd_service:
    name: docker.service
    state: restarted

- name: Reload isolated CTF executor SSH
  ansible.builtin.systemd_service:
    name: ssh.service
    state: reloaded
