apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
  annotations:
    metallb.io/loadBalancerIPs: "192.168.0.202"
spec:
  selector:
    app: speedtest-tracker
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  type: LoadBalancer