---
- name: Restart copyparty
  ansible.builtin.service:
    name: copyparty
    state: restarted

- name: Restart copyparty nftables
  ansible.builtin.service:
    name: nftables
    state: restarted
