http:
  routers:
    proxmox:
      rule: "Host(`pve.home.hchu.me`)"
      service: proxmox-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - local-network-only

    router:
      rule: "Host(`router.home.hchu.me`)"
      service: router-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - local-network-only

    printer:
      rule: "Host(`printer.home.hchu.me`)"
      service: printer-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - local-network-only

    dogtor:
      rule: "Host(`dogtor.hchu.me`)"
      service: dogtor-service
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - dogtor-cors

  middlewares:
    dogtor-cors:
      headers:
        accessControlAllowMethods:
          - "*"
        accessControlAllowOriginList:
          - "*"
        accessControlAllowHeaders:
          - "DNT"
          - "User-Agent"
          - "X-Requested-With"
          - "If-Modified-Since"
          - "Cache-Control"
          - "Content-Type"
          - "Range"
          - "Authorization"

  services:
    dogtor-service:
      loadBalancer:
        servers:
          - url: "http://3.35.140.63:8080"

    proxmox-service:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "https://192.168.0.2:8006"

    router-service:
      loadBalancer:
        servers:
          - url: "http://192.168.0.1"

    printer-service:
      loadBalancer:
        serversTransport: insecure
        servers:
          - url: "https://192.168.0.4"

  serversTransports:
    insecure:
      insecureSkipVerify: true
