http:
  middlewares:
    local-network-only:
      ipAllowList:
        sourceRange:
          - "192.168.0.0/24" # Local network
          - "127.0.0.1/32" # localhost
          - "10.0.0.0/8" # Private network
          - "172.16.0.0/12" # Private network
