http:
  middlewares:
    local-network-only:
      ipAllowList:
        sourceRange:
          - "192.168.0.0/24" # Local network
          - "127.0.0.1/32" # localhost
          - "10.0.0.0/8" # Private network
          - "172.16.0.0/12" # Private network
          - "100.64.0.0/10" # Tailscale/NetBird/CGNAT network

    rate-limit:
      rateLimit:
        average: 1000
        burst: 500
        period: 1m

    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        frameDeny: true
        browserXssFilter: true
