services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - open-webui:/app/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`openwebui.home.hchu.me`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.tls.certresolver=cloudflare"
      - "traefik.http.routers.openwebui.middlewares=local-network-only@file"
      - "traefik.http.routers.openwebui.service=openwebui"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
    environment:
      - CORS_ALLOW_ORIGIN=https://openwebui.home.hchu.me
volumes:
  open-webui:

networks:
  proxy:
    name: proxy