apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
  labels:
    app: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git:latest
        command:
        - sh
        - -c
        - |
          git clone https://github.com/holybaechu/homelab.git /repo
        volumeMounts:
        - name: repo
          mountPath: /repo
      containers:
      - name: glance
        image: glanceapp/glance:v0.8.4
        ports:
        - containerPort: 8080
          name: webui
        volumeMounts:
        - name: repo
          mountPath: /app/config
          subPath: apps/glance/config
      volumes:
      - name: repo
        emptyDir: {}