apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
  labels:
    app: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      initContainers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.4.2
          args:
          - --repo=https://github.com/holybaechu/homelab.git
          - --root=/repo
          - --dest=homelab
          - --one-time
          volumeMounts:
          - name: repo
            mountPath: /repo
      containers:
      - name: glance
        image: glanceapp/glance:v0.8.4
        ports:
        - containerPort: 8080
          name: webui
        env:
        - name: SPEEDTEST_URL
          value: https://speedtest.home.holyb.xyz
        - name: SPEEDTEST_TRACKER_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: glance-secrets
              key: SPEEDTEST_TRACKER_API_TOKEN
        - name: ADGUARD_USERNAME
          valueFrom:
            secretKeyRef:
              name: adguard-home-login
              key: username
        - name: ADGUARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adguard-home-login
              key: password
        - name: PROXMOXVE_URL
          value: https://pve.home.holyb.xyz
        - name: PROXMOXVE_KEY
          valueFrom:
            secretKeyRef:
              name: glance-secrets
              key: PROXMOXVE_KEY
        volumeMounts:
        - name: repo
          mountPath: /app/config
          subPath: homelab/apps/glance/config
          readOnly: true
        - name: repo
          mountPath: /app/assets
          subPath: homelab/apps/glance/assets
          readOnly: true
      volumes:
      - name: repo
        emptyDir: {}