apiVersion: v1
kind: Service
metadata:
  name: glance-webui
  namespace: glance
  annotations:
    metallb.io/loadBalancerIPs: "192.168.0.203"
spec:
  selector:
    app: glance
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer