apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/allow-ip-block: "192.168.0.0/24"
spec:
  tls:
    - hosts:
        - "argo.home.holyb.xyz"
      secretName: wildcard-holyb-xyz-tls
  ingressClassName: nginx
  rules:
    - host: "argo.home.holyb.xyz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443