---
- name: Configure Debian base
  hosts: debian
  gather_facts: true
  roles:
    - common_debian

- name: Configure tailnet LXC
  hosts: svc_tailnet
  gather_facts: true
  roles:
    - tailscale_gateway

- name: Configure Docker Compose application LXC
  hosts: svc_docker_apps
  gather_facts: true
  roles:
    - role: docker_engine
      tags: [docker_apps, docker_engine]
    - role: docker_compose_project
      tags: [docker_apps, compose]
