---
- name: Configure Alpine base
  hosts: alpine
  gather_facts: true
  roles:
    - common_alpine

- name: Configure Debian base
  hosts: debian
  gather_facts: true
  roles:
    - common_debian

- name: Configure edge LXC
  hosts: edge
  gather_facts: true
  roles:
    - caddy
    - ddns

- name: Configure DNS LXC
  hosts: dns
  gather_facts: true
  roles:
    - adguard_acme
    - adguard

- name: Configure tailnet LXC
  hosts: tailnet
  gather_facts: true
  roles:
    - tailscale_gateway
